package io.github.adiitgg.vertx.db.orm.processor.impl;

import io.github.adiitgg.vertx.db.orm.annotation.Id;
import io.github.adiitgg.vertx.db.orm.model.EntityFieldOptions;
import io.github.adiitgg.vertx.db.orm.processor.EntityAnnotationProcessor;

import java.lang.annotation.Annotation;

public class IdEntityAnnotationProcessor implements EntityAnnotationProcessor {

  @Override
  public boolean support(Annotation annotation) {
    return annotation instanceof Id;
  }

  @Override
  public void process(Annotation annotation, EntityFieldOptions options) {
    Id id = (Id) annotation;
    options.id(true);
    options.autoGeneratedId(id.autoGenerated());
  }

}
