package io.aitech.vertx.db.orm.model;

import lombok.Data;
import lombok.experimental.Accessors;

import java.util.HashMap;
import java.util.Map;
import java.util.function.Supplier;

@Data
@Accessors(fluent = true)
public class EntityFieldOptions {

  private boolean id;
  private boolean autoGeneratedId;
  private FieldWrapper fieldWrapper;
  private String columnName;
  private String defaultValue;
  private boolean nullable = true;
  private int length;
  private boolean insertable = true;
  private boolean updateable = true;
  private boolean isCreatedAt;
  private boolean isUpdatedAt;
  private boolean canConflict;
  private Class<?> serialized;

  private Supplier<Object> defaultValueProvider;

  private Map<String, Object> metadata;


  public Map<String, Object> metadata() {
    if (metadata == null) {
      this.metadata = new HashMap<>();
    }
    return metadata;
  }

  public EntityFieldOptions put(String key, Object value) {
    metadata().put(key, value);
    return this;
  }

  @SuppressWarnings("unchecked")
  public <T> T get(String key, T defaultValue) {
    return (T) metadata().getOrDefault(key, defaultValue);
  }

}
