package io.aitech.vertx.db.orm.annotation;

import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

/**
 * Specifies the column mapped by the annotated persistent property
 * or field.
 *
 * <p>If no {@code Column} annotation is explicitly specified, the
 * default values apply.
 *
 * <p>Example:
 * {@snippet :
 *
 * @Column(name = "DESC", nullable = false, length = 512)
 * public String getDescription() { return description; }
 *}
 * @since 1.0
 */
@Documented
@Target({METHOD, FIELD})
@Retention(RUNTIME)
public @interface Column {

  /**
   * (Optional) The name of the column. Defaults to the property
   * or field name.
   */
  String name() default "";

  /**
   * (Optional) Whether the database column is nullable.
   */
  boolean nullable() default true;

  /**
   * (Optional) Whether the column is included in SQL INSERT
   * statements generated by the persistence provider.
   */
  boolean insertable() default true;

  /**
   * (Optional) Whether the column is included in SQL UPDATE
   * statements generated by the persistence provider.
   */
  boolean updatable() default true;

  boolean canConflict() default false;

  /**
   * (Optional) The column length.
   * <p>
   * Applies only to columns whose type is parameterized by length,
   * for example, {@code varchar} or {@code varbinary} types.
   */
  int length() default 255;

}
