version: '3.8'

services:
  postgres-archtype:
    image: postgres:15
    container_name: postgres-archtype
    restart: unless-stopped
    environment:
      POSTGRES_DB: archtype
      POSTGRES_USER: archtype
      POSTGRES_PASSWORD: secret-password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - archtype-net

  postgres-archtype2:
    image: postgres:15
    container_name: postgres-archtype2
    restart: unless-stopped
    environment:
      POSTGRES_DB: archtype2
      POSTGRES_USER: archtype
      POSTGRES_PASSWORD: secret-password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data
    networks:
      - archtype-net

volumes:
  postgres_data:
  postgres_data2:

networks:
  archtype-net:
    driver: bridge
