name: Test Coverage with Coveralls

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Import GPG key and set trust
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf

          # Import private key
          echo "$GPG_PRIVATE_KEY" | gpg --batch --yes --import

          # Ambil key ID
          KEYID=$(gpg --list-secret-keys --with-colons | grep '^sec' | cut -d':' -f5)

          # Set trust (auto confirm)
          echo -e "5\ny\n" | gpg --command-fd 0 --batch --yes --pinentry-mode loopback --edit-key $KEYID trust

          echo "KEYID=$KEYID" >> $GITHUB_ENV
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Build and generate JaCoCo report
        run: mvn clean verify

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.6

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
